// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/database.proto

package databasepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Requests
type CreateNewUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewUserRequest) Reset() {
	*x = CreateNewUserRequest{}
	mi := &file_proto_database_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewUserRequest) ProtoMessage() {}

func (x *CreateNewUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_database_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewUserRequest.ProtoReflect.Descriptor instead.
func (*CreateNewUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_database_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNewUserRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CreateNewUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateNewUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to LoginMethod:
	//
	//	*LoginUserRequest_Username
	//	*LoginUserRequest_Email
	LoginMethod   isLoginUserRequest_LoginMethod `protobuf_oneof:"login_method"`
	Password      string                         `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserRequest) Reset() {
	*x = LoginUserRequest{}
	mi := &file_proto_database_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRequest) ProtoMessage() {}

func (x *LoginUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_database_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRequest.ProtoReflect.Descriptor instead.
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_database_proto_rawDescGZIP(), []int{1}
}

func (x *LoginUserRequest) GetLoginMethod() isLoginUserRequest_LoginMethod {
	if x != nil {
		return x.LoginMethod
	}
	return nil
}

func (x *LoginUserRequest) GetUsername() string {
	if x != nil {
		if x, ok := x.LoginMethod.(*LoginUserRequest_Username); ok {
			return x.Username
		}
	}
	return ""
}

func (x *LoginUserRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.LoginMethod.(*LoginUserRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *LoginUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type isLoginUserRequest_LoginMethod interface {
	isLoginUserRequest_LoginMethod()
}

type LoginUserRequest_Username struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3,oneof"`
}

type LoginUserRequest_Email struct {
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

func (*LoginUserRequest_Username) isLoginUserRequest_LoginMethod() {}

func (*LoginUserRequest_Email) isLoginUserRequest_LoginMethod() {}

type UpdatePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordRequest) Reset() {
	*x = UpdatePasswordRequest{}
	mi := &file_proto_database_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordRequest) ProtoMessage() {}

func (x *UpdatePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_database_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordRequest.ProtoReflect.Descriptor instead.
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return file_proto_database_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePasswordRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdatePasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_proto_database_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_database_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_database_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *UpdateRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type FindProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindProfileRequest) Reset() {
	*x = FindProfileRequest{}
	mi := &file_proto_database_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindProfileRequest) ProtoMessage() {}

func (x *FindProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_database_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindProfileRequest.ProtoReflect.Descriptor instead.
func (*FindProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_database_proto_rawDescGZIP(), []int{4}
}

func (x *FindProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetProfileInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileInfoRequest) Reset() {
	*x = GetProfileInfoRequest{}
	mi := &file_proto_database_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileInfoRequest) ProtoMessage() {}

func (x *GetProfileInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_database_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileInfoRequest.ProtoReflect.Descriptor instead.
func (*GetProfileInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_database_proto_rawDescGZIP(), []int{5}
}

func (x *GetProfileInfoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Responses
type BaseResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResultResponse) Reset() {
	*x = BaseResultResponse{}
	mi := &file_proto_database_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResultResponse) ProtoMessage() {}

func (x *BaseResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_database_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResultResponse.ProtoReflect.Descriptor instead.
func (*BaseResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_database_proto_rawDescGZIP(), []int{6}
}

func (x *BaseResultResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_proto_database_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_database_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_proto_database_proto_rawDescGZIP(), []int{7}
}

func (x *AuthResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type FindProfileBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Bio           string                 `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Banner        string                 `protobuf:"bytes,6,opt,name=banner,proto3" json:"banner,omitempty"`
	RegisteredAt  string                 `protobuf:"bytes,7,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindProfileBody) Reset() {
	*x = FindProfileBody{}
	mi := &file_proto_database_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindProfileBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindProfileBody) ProtoMessage() {}

func (x *FindProfileBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_database_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindProfileBody.ProtoReflect.Descriptor instead.
func (*FindProfileBody) Descriptor() ([]byte, []int) {
	return file_proto_database_proto_rawDescGZIP(), []int{8}
}

func (x *FindProfileBody) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FindProfileBody) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *FindProfileBody) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *FindProfileBody) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *FindProfileBody) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *FindProfileBody) GetBanner() string {
	if x != nil {
		return x.Banner
	}
	return ""
}

func (x *FindProfileBody) GetRegisteredAt() string {
	if x != nil {
		return x.RegisteredAt
	}
	return ""
}

type FindProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          []*FindProfileBody     `protobuf:"bytes,1,rep,name=body,proto3" json:"body,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindProfileResponse) Reset() {
	*x = FindProfileResponse{}
	mi := &file_proto_database_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindProfileResponse) ProtoMessage() {}

func (x *FindProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_database_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindProfileResponse.ProtoReflect.Descriptor instead.
func (*FindProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_database_proto_rawDescGZIP(), []int{9}
}

func (x *FindProfileResponse) GetBody() []*FindProfileBody {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *FindProfileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetProfileInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          *FindProfileBody       `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileInfoResponse) Reset() {
	*x = GetProfileInfoResponse{}
	mi := &file_proto_database_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileInfoResponse) ProtoMessage() {}

func (x *GetProfileInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_database_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileInfoResponse.ProtoReflect.Descriptor instead.
func (*GetProfileInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_database_proto_rawDescGZIP(), []int{10}
}

func (x *GetProfileInfoResponse) GetBody() *FindProfileBody {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *GetProfileInfoResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MyProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          *FindProfileBody       `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyProfileResponse) Reset() {
	*x = MyProfileResponse{}
	mi := &file_proto_database_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyProfileResponse) ProtoMessage() {}

func (x *MyProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_database_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyProfileResponse.ProtoReflect.Descriptor instead.
func (*MyProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_database_proto_rawDescGZIP(), []int{11}
}

func (x *MyProfileResponse) GetBody() *FindProfileBody {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *MyProfileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_database_proto protoreflect.FileDescriptor

const file_proto_database_proto_rawDesc = "" +
	"\n" +
	"\x14proto/database.proto\x12\bdatabase\x1a\x1bgoogle/protobuf/empty.proto\"d\n" +
	"\x14CreateNewUserRequest\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"t\n" +
	"\x10LoginUserRequest\x12\x1c\n" +
	"\busername\x18\x01 \x01(\tH\x00R\busername\x12\x16\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpasswordB\x0e\n" +
	"\flogin_method\"I\n" +
	"\x15UpdatePasswordRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"Q\n" +
	"\rUpdateRequest\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x03R\x06userId\"(\n" +
	"\x12FindProfileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"'\n" +
	"\x15GetProfileInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\",\n" +
	"\x12BaseResultResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\">\n" +
	"\fAuthResponse\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\"\xc0\x01\n" +
	"\x0fFindProfileBody\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x10\n" +
	"\x03bio\x18\x04 \x01(\tR\x03bio\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06banner\x18\x06 \x01(\tR\x06banner\x12#\n" +
	"\rregistered_at\x18\a \x01(\tR\fregisteredAt\"Z\n" +
	"\x13FindProfileResponse\x12-\n" +
	"\x04body\x18\x01 \x03(\v2\x19.database.FindProfileBodyR\x04body\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"]\n" +
	"\x16GetProfileInfoResponse\x12-\n" +
	"\x04body\x18\x01 \x01(\v2\x19.database.FindProfileBodyR\x04body\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"X\n" +
	"\x11MyProfileResponse\x12-\n" +
	"\x04body\x18\x01 \x01(\v2\x19.database.FindProfileBodyR\x04body\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xd5\x04\n" +
	"\x0fDatabaseService\x12B\n" +
	"\bRegister\x12\x1e.database.CreateNewUserRequest\x1a\x16.database.AuthResponse\x12;\n" +
	"\x05Login\x12\x1a.database.LoginUserRequest\x1a\x16.database.AuthResponse\x12O\n" +
	"\x0eUpdatePassword\x12\x1f.database.UpdatePasswordRequest\x1a\x1c.database.BaseResultResponse\x12F\n" +
	"\rUpdateProfile\x12\x17.database.UpdateRequest\x1a\x1c.database.BaseResultResponse\x12J\n" +
	"\vFindProfile\x12\x1c.database.FindProfileRequest\x1a\x1d.database.FindProfileResponse\x12S\n" +
	"\x0eGetProfileInfo\x12\x1f.database.GetProfileInfoRequest\x1a .database.GetProfileInfoResponse\x12I\n" +
	"\tMyProfile\x12\x1f.database.GetProfileInfoRequest\x1a\x1b.database.MyProfileResponse\x12<\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x1c.database.BaseResultResponseB\x12Z\x10proto/databasepbb\x06proto3"

var (
	file_proto_database_proto_rawDescOnce sync.Once
	file_proto_database_proto_rawDescData []byte
)

func file_proto_database_proto_rawDescGZIP() []byte {
	file_proto_database_proto_rawDescOnce.Do(func() {
		file_proto_database_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_database_proto_rawDesc), len(file_proto_database_proto_rawDesc)))
	})
	return file_proto_database_proto_rawDescData
}

var file_proto_database_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_database_proto_goTypes = []any{
	(*CreateNewUserRequest)(nil),   // 0: database.CreateNewUserRequest
	(*LoginUserRequest)(nil),       // 1: database.LoginUserRequest
	(*UpdatePasswordRequest)(nil),  // 2: database.UpdatePasswordRequest
	(*UpdateRequest)(nil),          // 3: database.UpdateRequest
	(*FindProfileRequest)(nil),     // 4: database.FindProfileRequest
	(*GetProfileInfoRequest)(nil),  // 5: database.GetProfileInfoRequest
	(*BaseResultResponse)(nil),     // 6: database.BaseResultResponse
	(*AuthResponse)(nil),           // 7: database.AuthResponse
	(*FindProfileBody)(nil),        // 8: database.FindProfileBody
	(*FindProfileResponse)(nil),    // 9: database.FindProfileResponse
	(*GetProfileInfoResponse)(nil), // 10: database.GetProfileInfoResponse
	(*MyProfileResponse)(nil),      // 11: database.MyProfileResponse
	(*emptypb.Empty)(nil),          // 12: google.protobuf.Empty
}
var file_proto_database_proto_depIdxs = []int32{
	8,  // 0: database.FindProfileResponse.body:type_name -> database.FindProfileBody
	8,  // 1: database.GetProfileInfoResponse.body:type_name -> database.FindProfileBody
	8,  // 2: database.MyProfileResponse.body:type_name -> database.FindProfileBody
	0,  // 3: database.DatabaseService.Register:input_type -> database.CreateNewUserRequest
	1,  // 4: database.DatabaseService.Login:input_type -> database.LoginUserRequest
	2,  // 5: database.DatabaseService.UpdatePassword:input_type -> database.UpdatePasswordRequest
	3,  // 6: database.DatabaseService.UpdateProfile:input_type -> database.UpdateRequest
	4,  // 7: database.DatabaseService.FindProfile:input_type -> database.FindProfileRequest
	5,  // 8: database.DatabaseService.GetProfileInfo:input_type -> database.GetProfileInfoRequest
	5,  // 9: database.DatabaseService.MyProfile:input_type -> database.GetProfileInfoRequest
	12, // 10: database.DatabaseService.Ping:input_type -> google.protobuf.Empty
	7,  // 11: database.DatabaseService.Register:output_type -> database.AuthResponse
	7,  // 12: database.DatabaseService.Login:output_type -> database.AuthResponse
	6,  // 13: database.DatabaseService.UpdatePassword:output_type -> database.BaseResultResponse
	6,  // 14: database.DatabaseService.UpdateProfile:output_type -> database.BaseResultResponse
	9,  // 15: database.DatabaseService.FindProfile:output_type -> database.FindProfileResponse
	10, // 16: database.DatabaseService.GetProfileInfo:output_type -> database.GetProfileInfoResponse
	11, // 17: database.DatabaseService.MyProfile:output_type -> database.MyProfileResponse
	6,  // 18: database.DatabaseService.Ping:output_type -> database.BaseResultResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_database_proto_init() }
func file_proto_database_proto_init() {
	if File_proto_database_proto != nil {
		return
	}
	file_proto_database_proto_msgTypes[1].OneofWrappers = []any{
		(*LoginUserRequest_Username)(nil),
		(*LoginUserRequest_Email)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_database_proto_rawDesc), len(file_proto_database_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_database_proto_goTypes,
		DependencyIndexes: file_proto_database_proto_depIdxs,
		MessageInfos:      file_proto_database_proto_msgTypes,
	}.Build()
	File_proto_database_proto = out.File
	file_proto_database_proto_goTypes = nil
	file_proto_database_proto_depIdxs = nil
}
