// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/database.proto

package databasepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateNewUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewUserRequest) Reset() {
	*x = CreateNewUserRequest{}
	mi := &file_proto_database_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewUserRequest) ProtoMessage() {}

func (x *CreateNewUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_database_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewUserRequest.ProtoReflect.Descriptor instead.
func (*CreateNewUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_database_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNewUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateNewUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateNewUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateNewUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewUserResponse) Reset() {
	*x = CreateNewUserResponse{}
	mi := &file_proto_database_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewUserResponse) ProtoMessage() {}

func (x *CreateNewUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_database_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewUserResponse.ProtoReflect.Descriptor instead.
func (*CreateNewUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_database_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNewUserResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type LoginUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to LoginMethod:
	//
	//	*LoginUserRequest_Username
	//	*LoginUserRequest_Email
	LoginMethod   isLoginUserRequest_LoginMethod `protobuf_oneof:"login_method"`
	Password      string                         `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserRequest) Reset() {
	*x = LoginUserRequest{}
	mi := &file_proto_database_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRequest) ProtoMessage() {}

func (x *LoginUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_database_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRequest.ProtoReflect.Descriptor instead.
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_database_proto_rawDescGZIP(), []int{2}
}

func (x *LoginUserRequest) GetLoginMethod() isLoginUserRequest_LoginMethod {
	if x != nil {
		return x.LoginMethod
	}
	return nil
}

func (x *LoginUserRequest) GetUsername() string {
	if x != nil {
		if x, ok := x.LoginMethod.(*LoginUserRequest_Username); ok {
			return x.Username
		}
	}
	return ""
}

func (x *LoginUserRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.LoginMethod.(*LoginUserRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *LoginUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type isLoginUserRequest_LoginMethod interface {
	isLoginUserRequest_LoginMethod()
}

type LoginUserRequest_Username struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3,oneof"`
}

type LoginUserRequest_Email struct {
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

func (*LoginUserRequest_Username) isLoginUserRequest_LoginMethod() {}

func (*LoginUserRequest_Email) isLoginUserRequest_LoginMethod() {}

type LoginUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserResponse) Reset() {
	*x = LoginUserResponse{}
	mi := &file_proto_database_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserResponse) ProtoMessage() {}

func (x *LoginUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_database_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserResponse.ProtoReflect.Descriptor instead.
func (*LoginUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_database_proto_rawDescGZIP(), []int{3}
}

func (x *LoginUserResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *LoginUserResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_database_proto protoreflect.FileDescriptor

const file_proto_database_proto_rawDesc = "" +
	"\n" +
	"\x14proto/database.proto\x12\bdatabase\"d\n" +
	"\x14CreateNewUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"/\n" +
	"\x15CreateNewUserResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"t\n" +
	"\x10LoginUserRequest\x12\x1c\n" +
	"\busername\x18\x01 \x01(\tH\x00R\busername\x12\x16\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpasswordB\x0e\n" +
	"\flogin_method\"A\n" +
	"\x11LoginUserResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xa0\x01\n" +
	"\x0fDatabaseService\x12K\n" +
	"\bRegister\x12\x1e.database.CreateNewUserRequest\x1a\x1f.database.CreateNewUserResponse\x12@\n" +
	"\x05Login\x12\x1a.database.LoginUserRequest\x1a\x1b.database.LoginUserResponseB\x12Z\x10proto/databasepbb\x06proto3"

var (
	file_proto_database_proto_rawDescOnce sync.Once
	file_proto_database_proto_rawDescData []byte
)

func file_proto_database_proto_rawDescGZIP() []byte {
	file_proto_database_proto_rawDescOnce.Do(func() {
		file_proto_database_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_database_proto_rawDesc), len(file_proto_database_proto_rawDesc)))
	})
	return file_proto_database_proto_rawDescData
}

var file_proto_database_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_database_proto_goTypes = []any{
	(*CreateNewUserRequest)(nil),  // 0: database.CreateNewUserRequest
	(*CreateNewUserResponse)(nil), // 1: database.CreateNewUserResponse
	(*LoginUserRequest)(nil),      // 2: database.LoginUserRequest
	(*LoginUserResponse)(nil),     // 3: database.LoginUserResponse
}
var file_proto_database_proto_depIdxs = []int32{
	0, // 0: database.DatabaseService.Register:input_type -> database.CreateNewUserRequest
	2, // 1: database.DatabaseService.Login:input_type -> database.LoginUserRequest
	1, // 2: database.DatabaseService.Register:output_type -> database.CreateNewUserResponse
	3, // 3: database.DatabaseService.Login:output_type -> database.LoginUserResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_database_proto_init() }
func file_proto_database_proto_init() {
	if File_proto_database_proto != nil {
		return
	}
	file_proto_database_proto_msgTypes[2].OneofWrappers = []any{
		(*LoginUserRequest_Username)(nil),
		(*LoginUserRequest_Email)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_database_proto_rawDesc), len(file_proto_database_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_database_proto_goTypes,
		DependencyIndexes: file_proto_database_proto_depIdxs,
		MessageInfos:      file_proto_database_proto_msgTypes,
	}.Build()
	File_proto_database_proto = out.File
	file_proto_database_proto_goTypes = nil
	file_proto_database_proto_depIdxs = nil
}
