// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/smtp.proto

package smtppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Requests
type SendOtpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOtpRequest) Reset() {
	*x = SendOtpRequest{}
	mi := &file_proto_smtp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOtpRequest) ProtoMessage() {}

func (x *SendOtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smtp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOtpRequest.ProtoReflect.Descriptor instead.
func (*SendOtpRequest) Descriptor() ([]byte, []int) {
	return file_proto_smtp_proto_rawDescGZIP(), []int{0}
}

func (x *SendOtpRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendOtpRequest) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

// Responses
type BaseResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResultResponse) Reset() {
	*x = BaseResultResponse{}
	mi := &file_proto_smtp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResultResponse) ProtoMessage() {}

func (x *BaseResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smtp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResultResponse.ProtoReflect.Descriptor instead.
func (*BaseResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_smtp_proto_rawDescGZIP(), []int{1}
}

func (x *BaseResultResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_proto_smtp_proto protoreflect.FileDescriptor

const file_proto_smtp_proto_rawDesc = "" +
	"\n" +
	"\x10proto/smtp.proto\x12\x04smtp\x1a\x1bgoogle/protobuf/empty.proto\":\n" +
	"\x0eSendOtpRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\",\n" +
	"\x12BaseResultResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2\x82\x01\n" +
	"\vSmtpService\x129\n" +
	"\aSendOtp\x12\x14.smtp.SendOtpRequest\x1a\x18.smtp.BaseResultResponse\x128\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x18.smtp.BaseResultResponseB\x0eZ\fproto/smtppbb\x06proto3"

var (
	file_proto_smtp_proto_rawDescOnce sync.Once
	file_proto_smtp_proto_rawDescData []byte
)

func file_proto_smtp_proto_rawDescGZIP() []byte {
	file_proto_smtp_proto_rawDescOnce.Do(func() {
		file_proto_smtp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_smtp_proto_rawDesc), len(file_proto_smtp_proto_rawDesc)))
	})
	return file_proto_smtp_proto_rawDescData
}

var file_proto_smtp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_smtp_proto_goTypes = []any{
	(*SendOtpRequest)(nil),     // 0: smtp.SendOtpRequest
	(*BaseResultResponse)(nil), // 1: smtp.BaseResultResponse
	(*emptypb.Empty)(nil),      // 2: google.protobuf.Empty
}
var file_proto_smtp_proto_depIdxs = []int32{
	0, // 0: smtp.SmtpService.SendOtp:input_type -> smtp.SendOtpRequest
	2, // 1: smtp.SmtpService.Ping:input_type -> google.protobuf.Empty
	1, // 2: smtp.SmtpService.SendOtp:output_type -> smtp.BaseResultResponse
	1, // 3: smtp.SmtpService.Ping:output_type -> smtp.BaseResultResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_smtp_proto_init() }
func file_proto_smtp_proto_init() {
	if File_proto_smtp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_smtp_proto_rawDesc), len(file_proto_smtp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_smtp_proto_goTypes,
		DependencyIndexes: file_proto_smtp_proto_depIdxs,
		MessageInfos:      file_proto_smtp_proto_msgTypes,
	}.Build()
	File_proto_smtp_proto = out.File
	file_proto_smtp_proto_goTypes = nil
	file_proto_smtp_proto_depIdxs = nil
}
