// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/scylla.proto

package scyllapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Requests
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_scylla_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scylla_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_scylla_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ChatMessage) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ChatMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatMessage) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type UploadMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMessagesRequest) Reset() {
	*x = UploadMessagesRequest{}
	mi := &file_proto_scylla_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMessagesRequest) ProtoMessage() {}

func (x *UploadMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scylla_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMessagesRequest.ProtoReflect.Descriptor instead.
func (*UploadMessagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_scylla_proto_rawDescGZIP(), []int{1}
}

func (x *UploadMessagesRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type UserId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserId) Reset() {
	*x = UserId{}
	mi := &file_proto_scylla_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserId) ProtoMessage() {}

func (x *UserId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scylla_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserId.ProtoReflect.Descriptor instead.
func (*UserId) Descriptor() ([]byte, []int) {
	return file_proto_scylla_proto_rawDescGZIP(), []int{2}
}

func (x *UserId) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// Responses
type BaseResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResultResponse) Reset() {
	*x = BaseResultResponse{}
	mi := &file_proto_scylla_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResultResponse) ProtoMessage() {}

func (x *BaseResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scylla_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResultResponse.ProtoReflect.Descriptor instead.
func (*BaseResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_scylla_proto_rawDescGZIP(), []int{3}
}

func (x *BaseResultResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ChatId        string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	SenderId      int64                  `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Edited        bool                   `protobuf:"varint,6,opt,name=edited,proto3" json:"edited,omitempty"`
	Deleted       bool                   `protobuf:"varint,7,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_scylla_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scylla_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_scylla_proto_rawDescGZIP(), []int{4}
}

func (x *Message) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Message) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *Message) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Message) GetEdited() bool {
	if x != nil {
		return x.Edited
	}
	return false
}

func (x *Message) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type Chats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	LastMessage   *Message               `protobuf:"bytes,2,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"`
	Participants  []int64                `protobuf:"varint,3,rep,packed,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chats) Reset() {
	*x = Chats{}
	mi := &file_proto_scylla_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chats) ProtoMessage() {}

func (x *Chats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scylla_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chats.ProtoReflect.Descriptor instead.
func (*Chats) Descriptor() ([]byte, []int) {
	return file_proto_scylla_proto_rawDescGZIP(), []int{5}
}

func (x *Chats) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *Chats) GetLastMessage() *Message {
	if x != nil {
		return x.LastMessage
	}
	return nil
}

func (x *Chats) GetParticipants() []int64 {
	if x != nil {
		return x.Participants
	}
	return nil
}

type ChatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*Chats               `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatsResponse) Reset() {
	*x = ChatsResponse{}
	mi := &file_proto_scylla_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatsResponse) ProtoMessage() {}

func (x *ChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scylla_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatsResponse.ProtoReflect.Descriptor instead.
func (*ChatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_scylla_proto_rawDescGZIP(), []int{6}
}

func (x *ChatsResponse) GetChats() []*Chats {
	if x != nil {
		return x.Chats
	}
	return nil
}

func (x *ChatsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_scylla_proto protoreflect.FileDescriptor

const file_proto_scylla_proto_rawDesc = "" +
	"\n" +
	"\x12proto/scylla.proto\x12\x06scylla\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x89\x01\n" +
	"\vChatMessage\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12.\n" +
	"\x04time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"H\n" +
	"\x15UploadMessagesRequest\x12/\n" +
	"\bmessages\x18\x01 \x03(\v2\x13.scylla.ChatMessageR\bmessages\"!\n" +
	"\x06UserId\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\",\n" +
	"\x12BaseResultResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"\xc9\x01\n" +
	"\aMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\x03R\bsenderId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x16\n" +
	"\x06edited\x18\x06 \x01(\bR\x06edited\x12\x18\n" +
	"\adeleted\x18\a \x01(\bR\adeleted\"x\n" +
	"\x05Chats\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x122\n" +
	"\flast_message\x18\x02 \x01(\v2\x0f.scylla.MessageR\vlastMessage\x12\"\n" +
	"\fparticipants\x18\x03 \x03(\x03R\fparticipants\"J\n" +
	"\rChatsResponse\x12#\n" +
	"\x05chats\x18\x01 \x03(\v2\r.scylla.ChatsR\x05chats\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xcb\x01\n" +
	"\rScyllaService\x12K\n" +
	"\x0eUploadMessages\x12\x1d.scylla.UploadMessagesRequest\x1a\x1a.scylla.BaseResultResponse\x121\n" +
	"\bGetChats\x12\x0e.scylla.UserId\x1a\x15.scylla.ChatsResponse\x12:\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x1a.scylla.BaseResultResponseB\x10Z\x0eproto/scyllapbb\x06proto3"

var (
	file_proto_scylla_proto_rawDescOnce sync.Once
	file_proto_scylla_proto_rawDescData []byte
)

func file_proto_scylla_proto_rawDescGZIP() []byte {
	file_proto_scylla_proto_rawDescOnce.Do(func() {
		file_proto_scylla_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scylla_proto_rawDesc), len(file_proto_scylla_proto_rawDesc)))
	})
	return file_proto_scylla_proto_rawDescData
}

var file_proto_scylla_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_scylla_proto_goTypes = []any{
	(*ChatMessage)(nil),           // 0: scylla.ChatMessage
	(*UploadMessagesRequest)(nil), // 1: scylla.UploadMessagesRequest
	(*UserId)(nil),                // 2: scylla.UserId
	(*BaseResultResponse)(nil),    // 3: scylla.BaseResultResponse
	(*Message)(nil),               // 4: scylla.Message
	(*Chats)(nil),                 // 5: scylla.Chats
	(*ChatsResponse)(nil),         // 6: scylla.ChatsResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_proto_scylla_proto_depIdxs = []int32{
	7, // 0: scylla.ChatMessage.time:type_name -> google.protobuf.Timestamp
	0, // 1: scylla.UploadMessagesRequest.messages:type_name -> scylla.ChatMessage
	4, // 2: scylla.Chats.last_message:type_name -> scylla.Message
	5, // 3: scylla.ChatsResponse.chats:type_name -> scylla.Chats
	1, // 4: scylla.ScyllaService.UploadMessages:input_type -> scylla.UploadMessagesRequest
	2, // 5: scylla.ScyllaService.GetChats:input_type -> scylla.UserId
	8, // 6: scylla.ScyllaService.Ping:input_type -> google.protobuf.Empty
	3, // 7: scylla.ScyllaService.UploadMessages:output_type -> scylla.BaseResultResponse
	6, // 8: scylla.ScyllaService.GetChats:output_type -> scylla.ChatsResponse
	3, // 9: scylla.ScyllaService.Ping:output_type -> scylla.BaseResultResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_scylla_proto_init() }
func file_proto_scylla_proto_init() {
	if File_proto_scylla_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scylla_proto_rawDesc), len(file_proto_scylla_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scylla_proto_goTypes,
		DependencyIndexes: file_proto_scylla_proto_depIdxs,
		MessageInfos:      file_proto_scylla_proto_msgTypes,
	}.Build()
	File_proto_scylla_proto = out.File
	file_proto_scylla_proto_goTypes = nil
	file_proto_scylla_proto_depIdxs = nil
}
