// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/scylla.proto

package scyllapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Requests
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_scylla_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scylla_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_scylla_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ChatMessage) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ChatMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UploadMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMessagesRequest) Reset() {
	*x = UploadMessagesRequest{}
	mi := &file_proto_scylla_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMessagesRequest) ProtoMessage() {}

func (x *UploadMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scylla_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMessagesRequest.ProtoReflect.Descriptor instead.
func (*UploadMessagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_scylla_proto_rawDescGZIP(), []int{1}
}

func (x *UploadMessagesRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

// Responses
type BaseResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResultResponse) Reset() {
	*x = BaseResultResponse{}
	mi := &file_proto_scylla_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResultResponse) ProtoMessage() {}

func (x *BaseResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scylla_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResultResponse.ProtoReflect.Descriptor instead.
func (*BaseResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_scylla_proto_rawDescGZIP(), []int{2}
}

func (x *BaseResultResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_proto_scylla_proto protoreflect.FileDescriptor

const file_proto_scylla_proto_rawDesc = "" +
	"\n" +
	"\x12proto/scylla.proto\x12\x06scylla\x1a\x1bgoogle/protobuf/empty.proto\"Y\n" +
	"\vChatMessage\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"H\n" +
	"\x15UploadMessagesRequest\x12/\n" +
	"\bmessages\x18\x01 \x03(\v2\x13.scylla.ChatMessageR\bmessages\",\n" +
	"\x12BaseResultResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2\x98\x01\n" +
	"\rScyllaService\x12K\n" +
	"\x0eUploadMessages\x12\x1d.scylla.UploadMessagesRequest\x1a\x1a.scylla.BaseResultResponse\x12:\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x1a.scylla.BaseResultResponseB\x10Z\x0eproto/scyllapbb\x06proto3"

var (
	file_proto_scylla_proto_rawDescOnce sync.Once
	file_proto_scylla_proto_rawDescData []byte
)

func file_proto_scylla_proto_rawDescGZIP() []byte {
	file_proto_scylla_proto_rawDescOnce.Do(func() {
		file_proto_scylla_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scylla_proto_rawDesc), len(file_proto_scylla_proto_rawDesc)))
	})
	return file_proto_scylla_proto_rawDescData
}

var file_proto_scylla_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_scylla_proto_goTypes = []any{
	(*ChatMessage)(nil),           // 0: scylla.ChatMessage
	(*UploadMessagesRequest)(nil), // 1: scylla.UploadMessagesRequest
	(*BaseResultResponse)(nil),    // 2: scylla.BaseResultResponse
	(*emptypb.Empty)(nil),         // 3: google.protobuf.Empty
}
var file_proto_scylla_proto_depIdxs = []int32{
	0, // 0: scylla.UploadMessagesRequest.messages:type_name -> scylla.ChatMessage
	1, // 1: scylla.ScyllaService.UploadMessages:input_type -> scylla.UploadMessagesRequest
	3, // 2: scylla.ScyllaService.Ping:input_type -> google.protobuf.Empty
	2, // 3: scylla.ScyllaService.UploadMessages:output_type -> scylla.BaseResultResponse
	2, // 4: scylla.ScyllaService.Ping:output_type -> scylla.BaseResultResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_scylla_proto_init() }
func file_proto_scylla_proto_init() {
	if File_proto_scylla_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scylla_proto_rawDesc), len(file_proto_scylla_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scylla_proto_goTypes,
		DependencyIndexes: file_proto_scylla_proto_depIdxs,
		MessageInfos:      file_proto_scylla_proto_msgTypes,
	}.Build()
	File_proto_scylla_proto = out.File
	file_proto_scylla_proto_goTypes = nil
	file_proto_scylla_proto_depIdxs = nil
}
